listen_port: 8083
web_port: 8081
web_host: 0.0.0.0

hardump: ./dumps/3ds-latest.har

client_certs: ./client-certificates/CTR-common.pem
ssl_insecure: true
tls_version_client_min: UNBOUNDED
tls_version_server_min: UNBOUNDED
