listen_port: 8083
web_port: 8081

hardump: ./pretendo-network-dump-3ds.har

client_certs: ./client-certificates/CTR-common.pem
ssl_insecure: true
tls_version_client_min: UNBOUNDED
tls_version_server_min: UNBOUNDED
