# See https://docs.mitmproxy.org/stable/concepts-options/ for documentation

listen_port: 8080
web_port: 8081

# Make sure that the right configuration files and certs are loaded
client_certs: ./client-certificates/WiiU-common.pem
confdir: ./.mitmproxy

# Enable the Pretendo redirection script
scripts: ["../pretendo_addon.py"]
pretendo_redirect: true
