# See https://docs.mitmproxy.org/stable/concepts-options/ for documentation

# An easy-to-remember port that should not conflict with anything
listen_port: 8888
web_port: 8089
mode: reverse:http://127.0.0.1:81
keep_host_header: true
block_global: false

# Disable HTTP/2 support, as it seems buggy and is not necessary
http2: false

# These just make sure that the right configuration files and certs are loaded.
client_certs: ./client-certificates/WiiU-common.pem
confdir: ./configuration

# This enables the Pretendo redirection script.
scripts: ["./pretendo_addon.py"]
pretendo_redirect: true

# A couple convenience features
console_focus_follow: true
showhost: true
console_palette: dark
console_layout: vertical
