# See https://docs.mitmproxy.org/stable/concepts-options/ for documentation

# An easy-to-remember port that should not conflict with anything
listen_port: 2240
web_port: 8088

# These settings make sure that connections are not blocked because they use an
# old version of TLS. This was probably the most annoying problem to solve for
# me. Note that not all of these settings are actually used; some are just for
# compatability with older versions and are ignored.
ssl_insecure: true
upstream_cert: false
tls_version_server_min: UNBOUNDED
tls_version_client_min: UNBOUNDED
ssl_version_server: all
ssl_version_client: all
ciphers_client: all
ciphers_server: all

# These just make sure that the right configuration files and certs are loaded.
client_certs: ./client-certificates
confdir: ./configuration

# This enables the Pretendo redirection script.
scripts: ./pretendo_addon.py

# This simply attempts makes sure that no requests are cached.
anticache: true

# A couple convenience features
console_focus_follow: true
showhost: true
console_palette: dark
