# See https://docs.mitmproxy.org/stable/concepts-options/ for documentation

# An easy-to-remember port that should not conflict with anything
listen_port: 2240
web_port: 8088

# These settings make sure that connections are not blocked because they use an
# old version of TLS.
ssl_insecure: true
tls_version_server_min: UNBOUNDED
tls_version_client_min: UNBOUNDED

# These just make sure that the right configuration files and certs are loaded.
client_certs: ./client-certificates/WiiU-common.pem
confdir: ./configuration

# This enables the Pretendo redirection script.
scripts: ["./pretendo_addon.py"]

# This simply attempts makes sure that no requests are cached.
anticache: true

# A couple convenience features
console_focus_follow: true
showhost: true
console_palette: dark
