name: Build Docker image

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --tag mitmproxy-pretendo

      - name: Save the Docker image
        run: docker save mitmproxy-pretendo -o mitmproxy-pretendo.tar

      - name: Upload the Docker image
        uses: actions/upload-artifact@v4
        with:
          name: mitmproxy-pretendo-docker-image-${{ github.sha }}
          path: mitmproxy-pretendo.tar
